name: Docker CI

on: [push, pull_request]

jobs:
  install_kbsdk_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: pull and run docker image
      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
      run: |
        docker pull ialarmedalien/kb-sdk
        mkdir -p bin
        docker run ialarmedalien/kb-sdk genscript > bin/kb-sdk
        chmod 755 bin/kb-sdk
        bin/kb-sdk test
